# Generated by Django 6.0.8 on 2026-08-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Historico', 'Sitio Histórico'), ('Cultural', 'Sitio Cultural / Galería / Museo'), ('Natural', 'Sitio Natural'), ('Taller', 'Taller Artesanal / Saber Popular'), ('Gastronomico', 'Gastronomía Tradicional')], default='Cultural', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden dentro del circuito')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_interes', to='codiselu.circuitocreativo')),
            ],
            options={
                'verbose_name': 'Punto de Interés',
                'verbose_name_plural': 'Puntos de Interés',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('Imagen', 'Imagen'), ('Video', 'Video')], default='Imagen', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/imagenes/')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube, Vimeo o servidor de video', null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='codiselu.ciudad')),
                ('punto_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='codiselu.puntointeres')),
            ],
            options={
                'verbose_name': 'Galería Multimedia',
                'verbose_name_plural': 'Galerías Multimedia',
            },
        ),
        migrations.CreateModel(
            name='DatoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Hito', 'Hito Histórico'), ('Leyenda', 'Mito o Leyenda'), ('SaberPopular', 'Saber Popular / Tradición'), ('Gastronomia', 'Dato Gastronómico')], default='Hito', max_length=20)),
                ('contenido', models.TextField()),
                ('epoca_o_ano', models.CharField(blank=True, help_text='Ej: Siglo XVI, 1912, Época Colonial', max_length=50, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_historicos', to='codiselu.ciudad')),
                ('punto_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_historicos', to='codiselu.puntointeres')),
            ],
            options={
                'verbose_name': 'Dato Histórico',
                'verbose_name_plural': 'Datos Históricos',
            },
        ),
    ]
