# Generated by Django 6.0.8 on 2026-08-08 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0002_puntointeres_galeriamultimedia_datohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPuntoVisitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('punto_interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_usuarios', to='codiselu.puntointeres')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_visitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto Visitado',
                'verbose_name_plural': 'Puntos Visitados',
                'db_table': 'usuario_puntos_visitados',
                'ordering': ['-fecha_visita'],
                'unique_together': {('usuario', 'punto_interes')},
            },
        ),
    ]
