# Generated by Django 6.0.8 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0003_usuariopuntovisitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopuntovisitado',
            name='distancia_metros',
            field=models.FloatField(blank=True, help_text='Distancia calculada en metros entre el usuario y el punto de interés', null=True),
        ),
        migrations.AddField(
            model_name='usuariopuntovisitado',
            name='es_validada',
            field=models.BooleanField(default=False, help_text='Indica si la visita fue validada por estar en/cerca del punto'),
        ),
        migrations.AddField(
            model_name='usuariopuntovisitado',
            name='latitud_usuario',
            field=models.FloatField(blank=True, help_text='Latitud GPS reportada por el usuario', null=True),
        ),
        migrations.AddField(
            model_name='usuariopuntovisitado',
            name='longitud_usuario',
            field=models.FloatField(blank=True, help_text='Longitud GPS reportada por el usuario', null=True),
        ),
    ]
