# Generated by Django 6.0.8 on 2026-08-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0004_usuariopuntovisitado_distancia_metros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Gastronomia', 'Gastronomía / Restaurante'), ('Hospedaje', 'Hotel / Hospedaje'), ('Taller', 'Taller Artesanal / Galería'), ('Destino', 'Destino Turístico / Sitio de Interés'), ('Servicios', 'Servicios Turísticos / Tours'), ('Otro', 'Otro')], default='Destino', max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='empresas/portadas/')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('acepta_inversiones', models.BooleanField(default=False, help_text='Indica si esta empresa o destino turístico acepta ofertas o proyectos de inversión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='codiselu.ciudad')),
                ('punto_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='codiselu.puntointeres')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa / Destino Turístico',
                'verbose_name_plural': 'Empresas y Destinos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(help_text='Dirección o punto del evento', max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('es_gratuito', models.BooleanField(default=True)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='codiselu.ciudad')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='codiselu.empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OportunidadInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('monto_requerido', models.DecimalField(decimal_places=2, help_text='Monto objetivo de inversión en USD o C$', max_digits=12)),
                ('monto_minimo_inversion', models.DecimalField(decimal_places=2, default=100.0, help_text='Monto mínimo para invertir', max_digits=12)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('retorno_estimado', models.CharField(blank=True, help_text='Ejemplo: 15% rendimiento anual, participación de utilidades', max_length=150, null=True)),
                ('tipo_inversor_permitido', models.CharField(choices=[('Todos', 'Nacionales y Extranjeros'), ('Nacional', 'Solo Nacionales'), ('Extranjero', 'Solo Extranjeros')], default='Todos', max_length=20)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_inversion', to='codiselu.empresa')),
            ],
            options={
                'verbose_name': 'Oportunidad de Inversión',
                'verbose_name_plural': 'Oportunidades de Inversión',
            },
        ),
        migrations.CreateModel(
            name='InversionTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_propuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_inversor', models.CharField(choices=[('Nacional', 'Turista / Inversionista Nacional'), ('Extranjero', 'Turista / Inversionista Extranjero')], default='Nacional', max_length=20)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje o propuesta enviada por el turista/inversionista', null=True)),
                ('telefono_inversor', models.CharField(blank=True, max_length=20, null=True)),
                ('email_inversor', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobada', 'Aprobada / Confirmada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('inversionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_inversion', to='codiselu.oportunidadinversion')),
            ],
            options={
                'verbose_name': 'Inversión de Turista',
                'verbose_name_plural': 'Inversiones de Turistas',
            },
        ),
    ]
