# Generated by Django 6.0.8 on 2026-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0005_empresa_evento_oportunidadinversion_inversionturista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='dias_previos_mural',
            field=models.PositiveIntegerField(default=7, help_text='Días antes de la fecha de inicio en los que el evento aparece en el mural de publicación'),
        ),
        migrations.AddField(
            model_name='evento',
            name='es_oficial',
            field=models.BooleanField(default=False, help_text='Indica si es un evento oficial de la ciudad publicado por administradores'),
        ),
    ]
