# Generated by Django 6.0.8 on 2026-08-13 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0006_evento_dias_previos_mural_evento_es_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='granos_cafe',
            field=models.ManyToManyField(blank=True, related_name='eventos_grano_cafe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galeriamultimedia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='codiselu.evento'),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='codiselu.ciudad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='codiselu.empresa')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='codiselu.evento')),
                ('likes', models.ManyToManyField(blank=True, related_name='publicaciones_dado_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/colecciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='codiselu.publicacion')),
            ],
            options={
                'verbose_name': 'Imagen de Publicación',
                'verbose_name_plural': 'Imágenes de Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='codiselu.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia a Evento',
                'verbose_name_plural': 'Asistencias a Eventos',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
