# Generated by Django 6.0.8 on 2026-08-20 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0007_evento_granos_cafe_galeriamultimedia_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicaciones', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='codiselu.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario de Publicación',
                'verbose_name_plural': 'Comentarios de Publicaciones',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
