# Generated by Django 6.0.8 on 2026-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0008_comentariopublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitocreativo',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='circuitocreativo',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='circuitocreativo',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='circuitocreativo',
            name='nombre_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='contenido_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='contenido_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='titulo_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='titulo_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Traducción al inglés', null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='descripcion_zh',
            field=models.TextField(blank=True, help_text='Traducción al mandarín', null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='nombre_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín', max_length=150, null=True),
        ),
    ]
