# Generated by Django 6.0.8 on 2026-09-07 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0009_circuitocreativo_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriamultimedia',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='Archivo de video local (mp4, mov, avi, webm, etc.)', null=True, upload_to='galeria/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm', 'wmv', 'flv', 'm4v'])]),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Archivo de imagen (jpg, png, webp, etc.)', null=True, upload_to='galeria/imagenes/'),
        ),
    ]
