# Generated by Django 6.0.8 on 2026-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0010_galeriamultimedia_video_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='rango_celebracion',
            field=models.CharField(blank=True, help_text="Descripción o rango aproximado (ej. 'Semana Santa (marzo/abril)', 'Primer fin de semana de agosto')", max_length=255, null=True, verbose_name='Rango o fecha de celebración'),
        ),
        migrations.AddField(
            model_name='evento',
            name='rango_celebracion_en',
            field=models.CharField(blank=True, help_text='Traducción al inglés del rango de celebración', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='rango_celebracion_zh',
            field=models.CharField(blank=True, help_text='Traducción al mandarín del rango de celebración', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='solo_este_ano',
            field=models.BooleanField(default=False, help_text='Marcar si este evento es exclusivo de este año y no una festividad recurrente anual', verbose_name='¿Solo este año?'),
        ),
    ]
