# Generated by Django 6.0.6 on 2026-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0011_evento_rango_celebracion_evento_rango_celebracion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitocreativo',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='circuitocreativo',
            name='nombre_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='contenido_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='datohistorico',
            name='titulo_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='rango_celebracion_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito del rango de celebración', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='oportunidadinversion',
            name='titulo_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='descripcion_miq',
            field=models.TextField(blank=True, help_text='Traducción al miskito', null=True),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='nombre_miq',
            field=models.CharField(blank=True, help_text='Traducción al miskito', max_length=150, null=True),
        ),
    ]
