# Generated by Django 6.0.6 on 2026-09-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_datos_retroactivos(apps, schema_editor):
    Empresa = apps.get_model('codiselu', 'Empresa')
    EmpresaMiembro = apps.get_model('codiselu', 'EmpresaMiembro')
    Publicacion = apps.get_model('codiselu', 'Publicacion')
    User = apps.get_model('codiselu', 'User')

    # 1. Backfill de EmpresaMiembro y condición de protagonista para creadores existentes
    for empresa in Empresa.objects.all():
        if empresa.usuario_id:
            EmpresaMiembro.objects.get_or_create(
                empresa_id=empresa.id,
                usuario_id=empresa.usuario_id,
                defaults={'rol': 'OWNER'}
            )
            User.objects.filter(id=empresa.usuario_id, es_protagonista=False).update(es_protagonista=True)

    # 2. Backfill de creado_por y tipo_autor en publicaciones existentes
    for pub in Publicacion.objects.all():
        changed = False
        if not pub.creado_por_id and pub.autor_id:
            pub.creado_por_id = pub.autor_id
            changed = True
        if pub.empresa_id and pub.tipo_autor != 'EMPRESA':
            pub.tipo_autor = 'EMPRESA'
            changed = True
        if changed:
            pub.save(update_fields=['creado_por', 'tipo_autor'])


def revertir_datos_retroactivos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0012_circuitocreativo_descripcion_miq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario real autenticado que realizó la publicación (auditoría)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_autor',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('EMPRESA', 'Empresa')], default='USUARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmpresaMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('EDITOR', 'Editor')], default='EDITOR', max_length=20)),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='codiselu.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Empresa',
                'verbose_name_plural': 'Miembros de Empresas',
                'db_table': 'empresa_miembros',
                'ordering': ['-fecha_incorporacion'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
        migrations.RunPython(migrar_datos_retroactivos, revertir_datos_retroactivos),
    ]
