# Generated by Django 6.0.6 on 2026-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0013_publicacion_creado_por_publicacion_tipo_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='circuitos',
            field=models.ManyToManyField(blank=True, help_text='Circuitos creativos donde la empresa tiene presencia o patrocinio', related_name='empresas_asociadas', to='codiselu.circuitocreativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_fin_publicidad',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la pauta publicitaria', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text='Número internacional de WhatsApp (ej: +50588888888)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiene_publicidad',
            field=models.BooleanField(default=False, help_text='Indica si la empresa cuenta con pauta publicitaria activa'),
        ),
    ]
