# Generated by Django 6.0.6 on 2026-10-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiselu', '0014_empresa_circuitos_empresa_fecha_fin_publicidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopublicacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicaciones', to='codiselu.empresa'),
        ),
        migrations.AddField(
            model_name='comentariopublicacion',
            name='tipo_autor',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('EMPRESA', 'Empresa')], default='USUARIO', max_length=20),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='empresa_likes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_dado_like', to='codiselu.empresa'),
        ),
    ]
